version: '2'
services:
  mongo:
    image: "newcrossfoodcoop/nxfc-mongo"
    ports:
      - "27017:27017"
  catalogue:
    image: "newcrossfoodcoop/nxfc_catalogue:latest" 
    ports:
      - "3010:3010"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    command: gulp api
  checkout:
    build: .
    volumes:
      - "./depends:/home/app/depends"
      - "./provides:/home/app/provides"
    ports:
      - "3030:3030"
      - "5858:5858"
    depends_on:
      - mongo
    environment:
      - CATALOGUE_HOSTNAME=catalogue
      - MONGO_HOSTNAME=mongo
      - DEBUG=depends:mongoose
    command: gulp
